# Generated by Django 5.1.6 on 2025-03-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Under Maintenance', 'Under Maintenance'), ('Decommissioned', 'Decommissioned')], default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(default='kgs', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('plant_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlantVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CultureBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('Incubation', 'Incubation'), ('Growth', 'Growth'), ('Ready', 'Ready'), ('Harvested', 'Harvested')], default='Incubation', max_length=50)),
                ('plant_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plantvariety')),
            ],
        ),
    ]
