# Generated by Django 5.1.6 on 2025-03-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturebatch',
            name='No_of_Bottles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
